apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iko.fullname" . }}
  labels:
    {{- include "iko.labels" . | nindent 4 }}
data:
  # Spring Boot configuratie
  SPRING_PROFILES_ACTIVE: {{ .Values.settings.spring.profiles.active | quote }}
  SERVER_PORT: {{ .Values.settings.iko.connectors.serverPort | quote }}
  
  # Database configuratie
  SPRING_DATASOURCE_URL: {{ .Values.settings.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.settings.spring.datasource.username | quote }}
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: {{ .Values.settings.spring.datasource.driverClassName | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: {{ .Values.settings.spring.jpa.properties.hibernateDialect }}
  
  # OAuth2 en Security configuratie
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI: {{ printf "%s/realms/%s" .Values.settings.keycloak.authServerURL .Values.settings.keycloak.realm | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID: {{ .Values.settings.keycloak.clientID | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: {{ printf "%s/realms/%s" .Values.settings.keycloak.authServerURL .Values.settings.keycloak.realm | quote }}
  
  # IKO bronnen configuratie
  IKO_CONNECTORS_BRP_HOST: {{ .Values.settings.iko.connectors.brp.host | quote }}
  IKO_CONNECTORS_BRP_SPECIFICATIONURI: {{ .Values.settings.iko.connectors.brp.specificationuri | quote }}
  IKO_CONNECTORS_OBJECTENAPI_HOST: {{ .Values.settings.iko.connectors.objects.host | quote }}
  IKO_CONNECTORS_OBJECTENAPI_SPECIFICATIONURI: {{ printf "%s/api/v2/schema/openapi.yaml" .Values.settings.iko.connectors.objects.host | quote }}
  IKO_CONNECTORS_OPENZAAK_HOST: {{ .Values.settings.iko.connectors.openzaak.host | quote }}
  IKO_CONNECTORS_OPENZAAK_CLIENTID: {{ .Values.settings.iko.connectors.openzaak.clientId | quote }}
  IKO_CONNECTORS_OPENZAAK_SPECIFICATIONURI: {{ .Values.settings.iko.connectors.openzaak.specificationuri | default ( printf "%s/zaken/api/v1/schema/openapi.yaml" .Values.settings.iko.connectors.openzaak.host ) | quote }}
  IKO_CONNECTORS_BAG_HOST: {{ .Values.settings.iko.connectors.bag.host | quote }}
  IKO_CONNECTORS_BAG_SPECIFICATIONURI: {{ .Values.settings.iko.connectors.bag.specificationuri | default ( printf "%s/lvbag/individuelebevragingen/v2/openapi.yaml" .Values.settings.iko.connectors.bag.host ) | quote }}
